### ISSUE TITLE
conditional FFmpeg output coloring

### ISSUE THREAD

**Issue by 9001** [lekoOwO/ytarchive-raw#3]
if FFmpeg exits normally (returncode 0), the output at the end should probably be an INFO instead of an ERROR.

This would make it easier to see when something actually goes wrong, and also makes normal runs less scary :p

Also maybe append a bit of text at the end saying "FFmpeg failed with error $RETURNCODE" at the end when it's nonzero?

**Comment by lekoOwO** [comment]
The coloring should be fixed. I totally agree with it.
As for the return code part, I think an error log is much helpful then the return code since the code does not provide very much info.
Maybe we can find a way to provide user error logs w/o occupying the whole screen lol
